/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "hsl(var(--bg))",
        surface: "hsl(var(--surface))",
        "text-primary": "hsl(var(--text))",
        muted: "hsl(var(--muted))",
        stroke: "hsl(var(--stroke))",
        accent: "hsl(var(--accent))",
        
        // Custom colors from Gwen OS UI
        "on-tertiary-fixed-variant": "#594400",
        "inverse-primary": "#6750a4",
        "on-surface-variant": "#cbc4d2",
        "surface-dim": "#141218",
        "on-error": "#690005",
        "on-secondary": "#342b4b",
        "on-primary": "#381e72",
        "secondary-fixed-dim": "#cdc0e9",
        "surface-container-lowest": "#0f0d13",
        "tertiary": "#e7c365",
        "on-secondary-container": "#bfb2da",
        "surface-container-highest": "#36343a",
        "background": "#141218",
        "error-container": "#93000a",
        "surface-container": "#211f24",
        "secondary-fixed": "#e9ddff",
        "surface-bright": "#3b383e",
        "on-tertiary-container": "#503d00",
        "tertiary-fixed": "#ffdf93",
        "inverse-on-surface": "#322f35",
        "outline": "#948e9c",
        "primary": "#cfbcff",
        "on-tertiary": "#3e2e00",
        "surface": "#141218",
        "surface-container-low": "#1d1b20",
        "surface-tint": "#cfbcff",
        "secondary": "#cdc0e9",
        "on-primary-fixed": "#22005d",
        "tertiary-fixed-dim": "#e7c365",
        "on-secondary-fixed-variant": "#4b4263",
        "tertiary-container": "#c9a74d",
        "on-secondary-fixed": "#1f1635",
        "on-background": "#e6e0e9",
        "primary-fixed": "#e9ddff",
        "on-surface": "#e6e0e9",
        "inverse-surface": "#e6e0e9",
        "primary-container": "#6750a4",
        "surface-container-high": "#2b292f",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#4f378a",
        "on-tertiary-fixed": "#241a00",
        "on-primary-container": "#e0d2ff",
        "primary-fixed-dim": "#cfbcff",
        "surface-variant": "#36343a",
        "secondary-container": "#4d4465",
        "error": "#ffb4ab",
        "outline-variant": "#494551"
      },
      fontFamily: {
        body: ["Inter", "sans-serif"],
        display: ["Instrument Serif", "serif"],
        "display-lg-mobile": ["Instrument Serif"],
        "label-sm": ["Inter"],
        "headline-md": ["Instrument Serif"],
        "body-md": ["Inter"],
        "display-lg": ["Instrument Serif"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "display-lg-mobile": ["48px", { lineHeight: "52px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["40px", { lineHeight: "48px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["80px", { lineHeight: "88px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
